config/routes.rb
Tutorialbeta::Application.routes.draw do
	
	resources :units
	resources :lessons

	root :to => "lessons#index"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_many :units
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	belongs_to :lesson
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	
	layout :choose_layout
	
	def index
		@lessons = Lesson.all
		
		flash.now[:notice] = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit,
			sed do eiusmod tempor incididunt ut labore et dolore magna
			aliqua. Ut enim ad minim veniam, quis nostrud exercitation
			ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
			aute irure dolor in reprehenderit in voluptate velit esse cillum 
			dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
			non proident, sunt in culpa qui officia deserunt mollit anim id est 
			laborum.'
								  
		respond_to do |format|
		format.html
		format.xml { render :xml => @lessons }
		end
		
		
	end
	
	def new
		@lesson = Lesson.new
		
		respond_to do |format|
		format.html
		format.xml { render :xml => @lesson }
		end
	end
	
	def create
		@lesson = Lesson.new(params[:lesson])
		
		respond_to do |format|
			if @lesson.save
				format.html { redirect_to(@lesson,
										:notice => 'Lesson was successfully created') }
				format.xml { render :xml => @lesson,
										:status => :created, :location => @post }
			else
				format.html { render :action => "new" }
				format.xml { render :xml => @lesson.errors,
										:status => :unprocessable_entity }
			end
		end
	end
	
	def show
		@lesson = Lesson.find(params[:id])
		@stage1	= @lesson.units.where( :stage_id => 1 )
		
		respond_to do |format|
			format.html
			format.xml { render :xml => @lesson }
		end
	end
	
	def edit
		@lesson = Lesson.find(params[:id])
		
		respond_to do |format|
			format.html
			format.xml { render :xml => @lesson }
		end
	end
	
	def update
		@lesson = Lesson.find(params[:id])
		
		respond_to do |format|
			if @lesson.update_attributes(params[:lesson])
				format.html { redirect_to @lesson,
										:notice => 'Lesson was successfully updated.'}
				format.xml { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml { render :xml => @lesson.errors,
										:status => :unprocessable_entity }
			end
		end
	end
	
	def destroy
		@lesson = Lesson.find(params[:id])
		@lesson.destroy
		
		respond_to do |format|
			format.html { redirect_to root_path }
			format.xml { head :ok }
		end
	end
	
	private
	
	def choose_layout
		if [ 'index', 'edit'].include? action_name
			'home'
		else
			'lesson'
		end
	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
	
	def index
		@units = Unit.all
		
		respond_to do |format|
			format.html
			format.xml { render :xml => @units }
		end
	end
	
	def new
		@unit = Unit.new
		
		respond_to do |format|
			format.html
			format.xml { render :xml => @unit }
		end
	end
	
	def create
		@unit = Unit.new(params[:unit])
		
		respond_to do |format|
			if @unit.save
				format.html { redirect_to( @unit,
										:notice => 'Unit was successfully created' )}
				format.xml { render :xml => @unit,
										:status => :created, :location => @unit }
			else
				format.html { render :action => "new" }
				format.xml { render :xml => @post.errors,
										:status => :unprocessable_entity }
			end
		end
	end
	
	def show
		@unit = Unit.find(params[:id])
		
		respond_to do |format|
			format.html
			format.xml { render :xml => @unit }
		end
	end
	
	def edit
		@unit = Unit.find(params[:id])
		
		respond_to do |format|
			format.html
			format.xml { render :xml => @unit }
		end
	end
	
	def update
		@unit = Unit.find(params[:id])
		
			respond_to do |format|
			if @unit.update_attributes(params[:unit])
				format.html { redirect_to(@unit,
										:notice => 'Unit was successfully updated') }
				format.xml { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml { render :xml => @unit.errors,
										:status => :unprocessable_entity }
			end
		end
	end
	
	def destroy
		@unit = Unit.find(params[:id])
		@unit.destroy
		
		respond_to do |format|
			format.html
			format.xml { head :ok }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorialbeta</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<nav>
		<div id="logo">
			<span></span>
		</div>
		<ul>
			<li><%= link_to 'html', '#' %></li>
			<li><%= link_to 'css', '#' %></li>
			<li><%= link_to 'ps', '#' %></li>
			<li><%= link_to 'jquery', '#' %></li>
			<li><%= link_to 'ruby', '#' %></li>
			<li><%= link_to 'rails', '#' %></li>
		</ul>
	</nav>
	<div class="container">
		<header>
		</header>
		<section>
		<%= yield %>
		</section>
		<footer>
		</footer>
	</div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorialbeta</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div class="container">
		<header>
			<% if notice %>
			<p id="notice"><%= notice %></p>
			<% end %>
		</header>
		<section>
		<%= yield %>
		</section>
		<footer>
		</footer>
	</div>
</body>
</html>

app/views/layouts/lesson.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorialbeta</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<nav>
		<div id="logo">
			<span></span>
		</div>
		<ul>
			<li><%= link_to 'html', '#' %></li>
			<li><%= link_to 'css', '#' %></li>
			<li><%= link_to 'ps', '#' %></li>
			<li><%= link_to 'jquery', '#' %></li>
			<li><%= link_to 'ruby', '#' %></li>
			<li><%= link_to 'rails', '#' %></li>
		</ul>
	</nav>
	<div class="container">
		<header>
			<div id="hd-title">
			<span><%= @lesson.subject %></span>
			</div>
			<div id="hd-description">
				<span>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
					do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut 
					enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
					ut.
				</span>
			</div>
		</header>
		<section>
		<%= yield %>
		</section>
		<footer>
		</footer>
	</div>
</body>
</html>

app/views/lessons/edit.html.erb
<%= form_for(@lesson) do |f| %>
	<div class="field">
		<%= f.label :subject %>
		<%= f.text_field :subject %>
	</div>
	<div class="field">
		<%= f.label :image %>
		<%= f.text_field :image %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/lessons/index.html.erb
<div id="homelessons">
	<ul>
		<% @lessons.each do |lesson| %>
		<li>
			<%= link_to image_tag(lesson.image), lesson_path(lesson) %>
		</li>
<% end %>
</div>

app/views/lessons/new.html.erb
<%= form_for(@lesson) do |f| %>
	<div class="field">
		<%= f.label :subject %>
		<%= f.text_field :subject %>
	</div>
	<div class="field">
		<%= f.label :image %>
		<%= f.text_field :image %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/lessons/show.html.erb
<div id="intro">
	<h2>Before you get started</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit,
			sed do eiusmod tempor incididunt ut labore et dolore magna
			aliqua. Ut enim ad minim veniam, quis nostrud exercitation
			ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
			aute irure dolor in reprehenderit in voluptate velit esse cillum 
			dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
			non proident, sunt in culpa qui officia deserunt mollit anim id est 
			laborum.
		</p>
</div>
<div id="stage-1">
	<h3>Stage 1: Getting familiar with <%= @lesson.subject %></h3>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit,
			sed do eiusmod tempor incididunt ut labore et dolore magna
			aliqua. Ut enim ad minim veniam, quis nostrud exercitation
			ullamco laboris nisi ut aliquip ex ea commodo consequat.
		</p>
		<div class="stageunits">
			<ul>
				<% @stage1.each do |stage| %>
				<li><%= stage.title %></li>
				<% end %>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
			</ul>
		</div>
</div>
<div id="stage-2">
	<h3>Stage 2: Getting familiar with Ruby</h3>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit,
			sed do eiusmod tempor incididunt ut labore et dolore magna
			aliqua. Ut enim ad minim veniam, quis nostrud exercitation
			ullamco laboris nisi ut aliquip ex ea commodo consequat.
		</p>
		<div class="stageunits">
			<ul>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
			</ul>
		</div>
</div>
<div id="stage-3">
	<h3>Stage 3: Getting familiar with Ruby</h3>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit,
			sed do eiusmod tempor incididunt ut labore et dolore magna
			aliqua. Ut enim ad minim veniam, quis nostrud exercitation
			ullamco laboris nisi ut aliquip ex ea commodo consequat.
		</p>
		<div class="stageunits">
			<ul>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
				<li><%= image_tag("tryruby.png") %></li>
			</ul>
		</div>
</div>


app/views/units/edit.html.erb
<%= form_for(@unit) do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :image %>
		<%= f.text_field :image %>
	</div>
	<div class="field">
		<%= f.label :stage_id %>
		<%= f.text_field :stage_id %>
	</div>
	<div class="field">
		<%= f.label :lesson_id %>
		<%= f.text_field :lesson_id %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/units/index.html.erb
<h1>This is the units index page</h1>
<% @units.each do |unit| %>
<%= image_tag(unit.image) %>
<% end %>

app/views/units/new.html.erb
<h1>Create a new unit</h1>

<%= form_for(@unit) do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :image %>
		<%= f.text_field :image %>
	</div>
	<div class="field">
		<%= f.label :stage_id %>
		<%= f.text_field :stage_id %>
	</div>
	<div class="field">
		<%= f.label :lesson_id %>
		<%= f.text_field :lesson_id %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/units/show.html.erb
<h1>This is the units index page</h1>
<%= image_tag(@unit.image) %><br />
<%= link_to "edit", edit_unit_path %>
<%= link_to "destroy", units_path, :method => :delete,
																 :confirm => 'Are you sure bro?' %>